apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: video-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: POSTGRES_DB
                  # ↑ Read POSTGRES_DB from the configmap we created
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: POSTGRES_PASSWORD
                  # ↑ Read password from secrets (decrypted automatically)
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1000m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: video-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432